#!/bin/bash

g++ -Wall -pedantic sa.cpp -O3 -o sa;
# 
# for f in `ls in3`; do 
# 	for tstart in `seq 25 20 200`; do
# 		for tend in `seq 10 10 50`; do
# 			if  [ $tend -lt $tstart ] ; then
# 				for eqi in `seq 50 10 100`; do
# 					for cool in 0.85 0.9 0.95; do
# 						for q in `seq 1 5`; do
# 							./sa in3/${f}  $tstart $tend $eqi $cool
# 						done;
# 					done;
# 				done;
# 			fi;
# 		done;
# 	done;
# done;





#for var in `seq 25 20 200`; do
#	./run2 1000 50 500 0.88
#done;


for var in `seq 100 100 10000`; do
	./run2 $var 50 500 0.88 |php prumer.php >> out3/tstrt
done;


for var in `seq 10 10 100`; do
	./run2 1000 $var 500 0.88 |php prumer.php >> out3/tend
done;


for var in `seq 100 10 1000`; do
	./run2 1000 50 $var 0.88 |php prumer.php >> out3/eqi
done;


for var in `seq 0.3 0.05 0.99`; do
	./run2 1000 50 500 $var |php prumer.php >> out3/cool
done;








